/**
 * ==================================================
 *   _____ _ _ _             _
 *  |     |_| | |___ ___ ___|_|_ _ _____
 *  | | | | | | | -_|   |   | | | |     |
 *  |_|_|_|_|_|_|___|_|_|_|_|_|___|_|_|_|
 *
 * ==================================================
 *
 * Copyright (c) 2025 Project Millennium
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <i18n.h>
#include <locale_data.h>       // generated by CMake from src/locales/*.json
#include <unordered_map>
#include <string>
#include <vector>
#include <nlohmann/json.hpp>

#ifdef _WIN32
#include <windows.h>
#endif

using TranslationMap = std::unordered_map<std::string, std::string>;

// ─── Embedded locale table ────────────────────────────────────────────────────

static const std::unordered_map<std::string, const char*> kEmbeddedLocales = {
    { "english",    kLocaleData_english    },
    { "russian",    kLocaleData_russian    },
    { "ukrainian",  kLocaleData_ukrainian  },
    { "german",     kLocaleData_german     },
    { "french",     kLocaleData_french     },
    { "spanish",    kLocaleData_spanish    },
    { "italian",    kLocaleData_italian    },
    { "polish",     kLocaleData_polish     },
    { "turkish",    kLocaleData_turkish    },
    { "swedish",    kLocaleData_swedish    },
    { "dutch",      kLocaleData_dutch      },
    { "brazilian",  kLocaleData_brazilian  },
    { "hungarian",  kLocaleData_hungarian  },
    { "indonesian", kLocaleData_indonesian },
    { "vietnamese", kLocaleData_vietnamese },
    { "schinese",   kLocaleData_schinese   },
    { "tchinese",   kLocaleData_tchinese   },
    { "japanese",   kLocaleData_japanese   },
    { "koreana",    kLocaleData_koreana    },
    { "latam",      kLocaleData_latam      },
    { "bulgarian",  kLocaleData_bulgarian  },
    { "danish",     kLocaleData_danish     },
};

// ─── Static state ─────────────────────────────────────────────────────────────

static std::string    s_currentLang = "english";
static TranslationMap s_currentTranslations;
static TranslationMap s_englishTranslations;

static const std::vector<Locale::Language> s_languages = {
    // Latin-script languages (sorted alphabetically for the dropdown)
    { "brazilian",  "Portugu\xC3\xAAs do Brasil"       },
    { "danish",     "Dansk"                             },
    { "dutch",      "Nederlands"                        },
    { "english",    "English"                           },
    { "french",     "Fran\xC3\xA7" "ais"               },
    { "german",     "Deutsch"                           },
    { "hungarian",  "Magyar"                            },
    { "indonesian", "Bahasa Indonesia"                  },
    { "italian",    "Italiano"                          },
    { "latam",      "Espa\xC3\xB1ol Latinoam."         },
    { "polish",     "Polski"                            },
    { "spanish",    "Espa\xC3\xB1ol"                   },
    { "swedish",    "Svenska"                           },
    { "turkish",    "T\xC3\xBCrk\xC3\xA7" "e"         },
    { "vietnamese", "Ti\xE1\xBA\xBFng Vi\xE1\xBB\x87t" },
    // Cyrillic-script languages
    { "bulgarian",  "\xD0\x91\xD1\x8A\xD0\xBB\xD0\xB3\xD0\xB0\xD1\x80\xD1\x81\xD0\xBA\xD0\xB8" },
    { "russian",    "\xD0\xA0\xD1\x83\xD1\x81\xD1\x81\xD0\xBA\xD0\xB8\xD0\xB9"                   },
    { "ukrainian",  "\xD0\xA3\xD0\xBA\xD1\x80\xD0\xB0\xD1\x97\xD0\xBD\xD1\x81\xD1\x8C\xD0\xBA\xD0\xB0" },
    // CJK languages (require CJK font support to render correctly)
    { "schinese",   "\xE7\xAE\x80\xE4\xBD\x93\xE4\xB8\xAD\xE6\x96\x87" },
    { "tchinese",   "\xE7\xB9\x81\xE9\xAB\x94\xE4\xB8\xAD\xE6\x96\x87" },
    { "japanese",   "\xE6\x97\xA5\xE6\x9C\xAC\xE8\xAA\x9E"              },
    { "koreana",    "\xED\x95\x9C\xEA\xB5\xAD\xEC\x96\xB4"              },
};

// ─── JSON parsing ─────────────────────────────────────────────────────────────

static TranslationMap ParseLocale(const char* jsonStr)
{
    TranslationMap result;
    if (!jsonStr || *jsonStr == '\0') return result;

    try {
        nlohmann::json j = nlohmann::json::parse(jsonStr);
        for (auto& [key, value] : j.items()) {
            if (value.is_string())
                result[key] = value.get<std::string>();
        }
    } catch (...) {}

    return result;
}

static TranslationMap LoadLanguage(const std::string& langId)
{
    auto it = kEmbeddedLocales.find(langId);
    if (it == kEmbeddedLocales.end()) return {};
    return ParseLocale(it->second);
}

// ─── Platform language detection ──────────────────────────────────────────────

static std::string DetectFromLangString(const std::string& lang)
{
    if (lang.size() < 2) return "english";
    std::string code = lang.substr(0, 2);

    if (code == "ru") return "russian";
    if (code == "uk") return "ukrainian";
    if (code == "de") return "german";
    if (code == "fr") return "french";
    if (code == "it") return "italian";
    if (code == "pl") return "polish";
    if (code == "tr") return "turkish";
    if (code == "bg") return "bulgarian";
    if (code == "sv") return "swedish";
    if (code == "nl") return "dutch";
    if (code == "hu") return "hungarian";
    if (code == "id") return "indonesian";
    if (code == "vi") return "vietnamese";
    if (code == "da") return "danish";
    if (code == "ja") return "japanese";
    if (code == "ko") return "koreana";
    if (code == "pt") return "brazilian";  // pt_PT falls back to Brazilian (closest available)
    if (code == "es") {
        // es_MX, es_AR, etc. → latam; es_ES → spanish
        if (lang.size() >= 5 && (lang.substr(3, 2) == "ES" || lang.substr(3, 2) == "es"))
            return "spanish";
        return "latam";
    }
    if (code == "zh") {
        // zh_CN → schinese, zh_TW → tchinese
        if (lang.size() >= 5 && (lang.substr(3, 2) == "TW" || lang.substr(3, 2) == "tw"
                               || lang.substr(3, 2) == "HK" || lang.substr(3, 2) == "hk"))
            return "tchinese";
        return "schinese";
    }
    return "english";
}

std::string Locale::DetectSystemLanguage()
{
#ifdef _WIN32
    LANGID langId  = GetUserDefaultUILanguage();
    WORD primary   = PRIMARYLANGID(langId);
    WORD sub       = SUBLANGID(langId);

    switch (primary) {
        case LANG_RUSSIAN:    return "russian";
        case LANG_UKRAINIAN:  return "ukrainian";
        case LANG_GERMAN:     return "german";
        case LANG_FRENCH:     return "french";
        case LANG_ITALIAN:    return "italian";
        case LANG_POLISH:     return "polish";
        case LANG_TURKISH:    return "turkish";
        case LANG_BULGARIAN:  return "bulgarian";
        case LANG_SWEDISH:    return "swedish";
        case LANG_DUTCH:      return "dutch";
        case LANG_HUNGARIAN:  return "hungarian";
        case LANG_INDONESIAN: return "indonesian";
        case LANG_VIETNAMESE: return "vietnamese";
        case LANG_DANISH:     return "danish";
        case LANG_JAPANESE:   return "japanese";
        case LANG_KOREAN:     return "koreana";
        case LANG_SPANISH:
            // SUBLANG_SPANISH = 1 (Spain), anything else = Latin America
            return (sub == SUBLANG_SPANISH) ? "spanish" : "latam";
        case LANG_PORTUGUESE:
            // pt_PT falls back to Brazilian (closest available)
            return "brazilian";
        case LANG_CHINESE:
            // SUBLANG_CHINESE_SIMPLIFIED = 2, SUBLANG_CHINESE_TRADITIONAL = 1
            return (sub == SUBLANG_CHINESE_SIMPLIFIED) ? "schinese" : "tchinese";
        default:              return "english";
    }
#else
    const char* lang = getenv("LANG");
    if (!lang) lang = getenv("LANGUAGE");
    if (!lang) return "english";
    return DetectFromLangString(std::string(lang));
#endif
}

// ─── Public API ───────────────────────────────────────────────────────────────

void Locale::Initialize()
{
    s_englishTranslations = LoadLanguage("english");
    s_currentLang         = DetectSystemLanguage();
    s_currentTranslations = (s_currentLang == "english")
                          ? s_englishTranslations
                          : LoadLanguage(s_currentLang);
}

void Locale::SetLanguage(const std::string& langId)
{
    s_currentLang         = langId;
    s_currentTranslations = (langId == "english")
                          ? s_englishTranslations
                          : LoadLanguage(langId);
}

const std::string& Locale::GetCurrentLanguageId()
{
    return s_currentLang;
}

const char* Locale::Get(const std::string& key)
{
    {
        auto it = s_currentTranslations.find(key);
        if (it != s_currentTranslations.end())
            return it->second.c_str();
    }
    {
        auto it = s_englishTranslations.find(key);
        if (it != s_englishTranslations.end())
            return it->second.c_str();
    }
    return key.c_str();
}

const std::vector<Locale::Language>& Locale::GetAvailableLanguages()
{
    return s_languages;
}

bool Locale::UsesCyrillic()
{
    return s_currentLang == "russian"  || s_currentLang == "ukrainian"
        || s_currentLang == "bulgarian";
}

bool Locale::UsesCJK()
{
    return s_currentLang == "japanese"  || s_currentLang == "schinese"
        || s_currentLang == "tchinese"  || s_currentLang == "koreana";
}
